### PR TITLE
feat: Initial work on making django-backup compatible with Python 3

### PR DESCRIPTION
**Pull request by zerok**
This also removes the dependency on the forked version of pysftp in favour of using the official project.

### CODE REVIEW

**Comment by andybak** [comment]
I actually thought the pysftp dependency was already removed. I took that out of the readme in a recent tweak. So - good job you've done this now!

**Comment by zerok** [comment]
I also covered it in the tests :-) Now I just have to resolve the merge conflict I have product all by myself ;-)

**Comment by zerok** [comment]
Grrr... just noticed that I forgot to update the .travis.yml file. Need to do that before this could be merged.

**Comment by zerok** [comment]
Done :-)

@andybak if you don't mind, I'll merge this then and continue with some of the other cleanup-tasks for 2.0.

**Comment by andybak** [comment]
Sure!

**Pull request merged**
