### PR TITLE
Backup data without structure

### PR DESCRIPTION
**Pull request by adi-**
pg_dump should backup only DB data without any structure, since it is recreated by Django migrations itself.

### CODE REVIEW

**Comment by andybak** [comment]
I can see two sides to this debate:
1. backup should restore the database EXACTLY how it was when the backup was taken
2. backup should restore just data

Currently we are aiming for 1 - but we don't succeed unless the user deletes and recreates the db each time. There's also issues on Postgres with restoring to a different db/schema which is something that's incredibly useful and should be supported.

Your option 2 makes me nervous. I've seen many cases where the schema has drifted away from how Django thinks it should be. Is it django-backup's job to get involved in this? Just restoring the db is the most neutral course of action. It's a snapshot of a point in time. If we return to it then we are following the 'principle of least harm'.

If we just restore data - how about the migrations table itself? Are we restoring the db to the schema when the dump was taken or the schema as it is now?

**Comment by andybak** [comment]
I'd be happy with a switch so that the behaviour was optional. I'd also like a solution to restoring pg dumps to a different db name or schema name if you can solve that at the same time!

**Comment by adi-** [comment]
> Your option 2 makes me nervous.

:)

> Just restoring the db is the most neutral course of action. It's a snapshot of a point in time. If we return to it then we are following the 'principle of least harm'. If we just restore data - how about the migrations table itself? Are we restoring the db to the schema when the dump was taken or the schema as it is now?

I think there isn't any right approach. My change fixes an error, when restore sql is trying to drop parts of the schema when using or not using migrate mechanism. This functionality is managed by Django itself, usually by its migrate system and shouldn't be restored by db backup script. Otherwise, many functional errors could arise.

I have doubts if someone wants to restore their databases to some point in history. This is ridiculous, because their app will be broken after changes in their model. Correct me if I am wrong, but in case of using Django ORM there is no way to go back to some point in history. You will use functionality (added by the time) restoring the code and db.

I think django-backup (and other simillar aps) are mainly developed for restoring systems after critical errors. That's it. Otherwise, non of any automated-backup systems will help you in seconds.

> I'd be happy with a switch so that the behaviour was optional. I'd also like a solution to restoring pg dumps to a different db name or schema name if you can solve that at the same time!

This is a good idea. Another parameter to drop data only. Shall I fix that?

**Comment by andybak** [comment]
>  My change fixes an error, when restore sql is trying to drop parts of the schema when using or not using migrate mechanism

Can you give me more info? I know there are a few postgres problems but the basic principle is sound. I've been using it on MySQL for years.

> I have doubts if someone wants to restore their databases to some point in history. 

I do this all the time. Mainly bringing production data (which is based on an older version of the code) into a development server. It works fine. You restore the db to how it used to be, run ./manage.py migrate and everything works. The fact that the current migration is stored with the data is what makes it work.

> I think django-backup (and other simillar aps) are mainly developed for restoring systems after critical errors. 

This is it's most valuable function but one that I've never had to use so far - because we've never had a db failure. However - I use it as a tool to grab and load snapshots of the db from various servers several times a week.

**Comment by andybak** [comment]
> This is a good idea. Another parameter to drop data only. Shall I fix that?

Yes please.

**Comment by adi-** [comment]
> Can you give me more info? I know there are a few postgres problems but the basic principle is sound. I've been using it on MySQL for years.

Errors like:
- constraint "..." of relation "..." does not exist
- cannot drop constraint "..." because other objects depend on it
- constraint "..." on table "..." depends on index "...". HINT:  Use DROP ... CASCADE to drop the dependent objects too.
-  schema "public" already exists
- relation "..." already exists
- multiple primary keys for table "..." are not allowed

and of course errors due to system/user privilages:
- must be owner of extension plpgsql
- must be owner of schema public

As you can see, a lot of mess is generated with ERRORS.

**Comment by adi-** [comment]
You know what, I totally fucked up the idea. You are right, that all DB data should be restored. I have probably experienced brain blackout or something.

My last and ONLY concern now is, if `--clean` should be used in `pg_dumb` or maybe I ask to many questions? :+1:

**Comment by adi-** [comment]
Since you are restoring your DB `--clean` will generate errors.

**Comment by andybak** [comment]
```
--clean
Output commands to clean (drop) database objects prior to outputting the commands
for creating them. (Restore might generate some harmless errors.)
```

So I'm guessing that's OK. However I would love the pg dump to be in a format where I can restore it to a different schema or db name - the same way mysql works.

Any ideas?

**Comment by adi-** [comment]
> I would love the pg dump to be in a format where I can restore it to a different schema or db name - the same way mysql works. Any ideas?

Restoring to different DB is quite simple. Changing:

``` python
#restore.py 138:
args.append(self.db)
```

to something like

``` python
#restore.py 138:
if self.new_db # new_db comes from restore parameter variable
    args.append(self.new_db)
else:
    args.append(self.db)
```

should do the work. However restoring DB to different schema is not a simple task. It can be reproduced only with hacking techniques, messing with sql file etc. It stinks!

**Comment by adi-** [comment]
Missing `-d` param:

``` python
#restore.py 138:
if self.new_db # new_db comes from restore parameter variable
    args.append('-d', self.new_db)
else:
    args.append(self.db)
```

**Comment by adi-** [comment]
Of course if credentials in the new DB are different, they also should be obtained from resotre params.

**Pull request closed without merging**
